--dim_date
SELECT
    ORDER_DATE AS DATE,
    YEAR(ORDER_DATE) AS YEAR,
    MONTH(ORDER_DATE) AS MONTH,
    DAY(ORDER_DATE) AS DAY,
    DAYOFWEEK(ORDER_DATE) AS WEEKDAY
FROM {{ ref('fact_sales_orders') }}
WHERE ORDER_DATE IS NOT NULL
GROUP BY ORDER_DATE
