SELECT 
  SOD.SALES_ORDER_ID,
  SOD.SALES_ORDER_DETAIL_ID,
  SOD.CARRIER_TRACKING_NUMBER,
  SOD.ORDER_QUANTITY,
  SOD.PRODUCT_ID,
  SOD.PRODUCT_NAME,
  SOD.SPECIAL_OFFER_ID,
  SOD.UNIT_PRICE,
  SOD.UNIT_PRICE_DISCOUNT,
  SOD.LINE_TOTAL,
  SOD.MODIFIED_DATE,
  SOD.UPDATE_DATE
FROM {{ ref('silver_sales_order_details') }} SOD
