SELECT 
  SOD.SALES_ORDER_ID,
  SOD.SALES_ORDER_DETAIL_ID, 
  SOD.PRODUCT_ID,
  SOD.PRODUCT_NAME,
  SOH.CUSTOMER_ID,
  SOH.ORDER_DATE,
  SOD.ORDER_QUANTITY,
  SOD.UNIT_PRICE,
  SOD.UNIT_PRICE_DISCOUNT,
  SOD.LINE_TOTAL  
FROM {{ ref('silver_sales_order_details') }} SOD
LEFT JOIN {{ ref('silver_sales_orders') }} SOH
ON SOH.SALES_ORDER_ID = SOD.SALES_ORDER_ID
WHERE SOH.SALES_ORDER_ID IS NOT NULL
  AND SOD.SALES_ORDER_DETAIL_ID IS NOT NULL