  SELECT
    productId             AS PRODUCT_ID,
    name                  AS NAME,
    productNumber         AS PRODUCT_NUMBER,
    isManufactured        AS IS_MANUFACTURED_FLAG,
    isSaleable            AS IS_SALEABLE_FLAG,
    color                 AS COLOR,
    safetyStockLevel      AS SAFETY_STOCK_LEVEL,
    reorderPoint          AS REORDER_POINT,
    standardCost          AS STANDARD_COST,
    listPrice             AS LIST_PRICE,
    size                  AS SIZE,
    sizeUnit              AS SIZE_UNIT,
    weightUnit            AS WEIGHT_UNIT,
    weight                AS WEIGHT,
    daysToManufacture     AS DAYS_TO_MANUFACTURE,
    productLine           AS PRODUCT_LINE,
    class                 AS CLASS,
    style                 AS STYLE,
    subcategory           AS SUBCATEGORY,
    category              AS CATEGORY,
    MODEL                 AS MODEL,
    date({{ from_utc_to_WA('sellStartDate') }})     AS SELL_START_DATE,
    date({{ from_utc_to_WA('sellEndDate') }})       AS SELL_END_DATE,
    date({{ from_utc_to_WA('discontinuedDate') }})  AS DISCONTINUED_DATE,
    {{ from_utc_to_WA() }}                        AS MODIFIED_DATE,
    {{ from_utc_to_WA(current_timestamp()) }}     AS UPDATE_DATE
FROM {{ source('bronze_adworks_rich', 'products') }}
WHERE productId IS NOT NULL 